//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antifraud.Common.Globalization {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Antifraud.Common.Globalization.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cuenta origen es inválida..
        /// </summary>
        public static string InvalidSourceAccount {
            get {
                return ResourceManager.GetString("InvalidSourceAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cuenta destino es inválida..
        /// </summary>
        public static string InvalidTargetAccount {
            get {
                return ResourceManager.GetString("InvalidTargetAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El monto de la transacción es inválido..
        /// </summary>
        public static string InvalidTransactionAmount {
            get {
                return ResourceManager.GetString("InvalidTransactionAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El parámetro {0} es requerido..
        /// </summary>
        public static string ParameterRequired {
            get {
                return ResourceManager.GetString("ParameterRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La transacción proporcionada es inválida y no puede ser procesada..
        /// </summary>
        public static string RejectionInvalidTransaction {
            get {
                return ResourceManager.GetString("RejectionInvalidTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El acumulado en transacciones por día excede el límite permitido..
        /// </summary>
        public static string RejectionMaxTransactionAllowed {
            get {
                return ResourceManager.GetString("RejectionMaxTransactionAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El monto de la transacción no puede ser mayor a 2,000..
        /// </summary>
        public static string RejectionMaxValueExceeded {
            get {
                return ResourceManager.GetString("RejectionMaxValueExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado un evento con los parámetros proporcionados..
        /// </summary>
        public static string TransactionEventNotFound {
            get {
                return ResourceManager.GetString("TransactionEventNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado la transaccion con los parámetros especificados..
        /// </summary>
        public static string TransactionNotFound {
            get {
                return ResourceManager.GetString("TransactionNotFound", resourceCulture);
            }
        }
    }
}
